apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ticket
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: belajar-microservice
  artifacts:
    - image: omenology/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: omenology/client
      context: client/ticketing
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "**/*.ts"
          - "**/*.tsx"
          - "**/*.css"
    - image: omenology/ticket
      context: ticket
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: omenology/order
      context: order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: omenology/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*.yml
# kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asdf
