apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ticket
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-355304
  artifacts:
    - image: asia.gcr.io/ticketing-dev-355304/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

deploy:
  kubectl:
    manifests:
      - infra/k8s/*
