apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ticket
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: belajar-microservice
  artifacts:
    - image: asia.gcr.io/belajar-microservice/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: asia.gcr.io/belajar-microservice/client
      context: client/ticketing
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "**/*.ts"
          - "**/*.tsx"
          - "**/*.css"
    - image: asia.gcr.io/belajar-microservice/ticket
      context: ticket
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

deploy:
  kubectl:
    manifests:
      - infra/k8s/*.yml
# kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asdf
