apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "auth-mongo-srv"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "root"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "password"

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-srv
spec:
  selector:
    app: mongo-express
  type: ClusterIP
  ports:
    - name: mongo-express
      protocol: TCP
      port: 8081
      targetPort: 8081
