name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Build and push auth service
      uses: docker/build-push-action@v3
      with:
        context: ./auth
        push: true
        tags: omenology/auth:latest
      
    - name: Build and push order service
      uses: docker/build-push-action@v3
      with:
        context: ./order
        push: true
        tags: omenology/order:latest
      
    - name: Build and push ticket service
      uses: docker/build-push-action@v3
      with:
        context: ./ticket
        push: true
        tags: omenology/ticket:latest
        
    - name: Build and push client service
      uses: docker/build-push-action@v3
      with:
        context: ./client/ticketing
        push: true
        tags: omenology/client:latest
      
      
